/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ogengpress;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Yajong
 */
public class FormDataTrans extends javax.swing.JFrame {

    /**
     * Creates new form FormDataTrans
     */
    Database db = new Database();
    DefaultTableModel model = new DefaultTableModel();
    
    public FormDataTrans() {
        initComponents();
        db.koneksi();
        
        // Fullscreen 
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
        
        aturTabel();
        tampilkanData();
        designButton();
        shortcutApp();
    }
    
    private void designButton(){
        btn_cari.setOpaque(true);
        btn_cari.setContentAreaFilled(true);
        btn_cari.setBorderPainted(false);
        btn_cari.setBackground(new Color(51,153,255));
        
        btn_refresh.setOpaque(true);
        btn_refresh.setContentAreaFilled(true);
        btn_refresh.setBorderPainted(false);
        btn_refresh.setBackground(new Color(102,255,102));
        
        btn_kembali.setOpaque(true);
        btn_kembali.setContentAreaFilled(true);
        btn_kembali.setBorderPainted(false);
        btn_kembali.setBackground(new Color(255,204,204));
    }
    
    private void shortcutApp(){
        InputMap inputMap = rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = rootPane.getActionMap();
        
        inputMap.put(KeyStroke.getKeyStroke("alt F1"), "cari");
        actionMap.put("cari", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
               btn_cari.doClick();
            }
        });
        
        inputMap.put(KeyStroke.getKeyStroke("alt F2"), "refresh");
        actionMap.put("refresh", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
               btn_refresh.doClick();
            }
        });
        
        inputMap.put(KeyStroke.getKeyStroke("alt F3"), "kembali");
        actionMap.put("kembali", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
               btn_kembali.doClick();
            }
        });
    }
    
    private void aturTabel(){
        model.addColumn("No Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("Total");
        model.addColumn("Bayar");
        model.addColumn("Kembali");
        tbl_data.setModel(model);
        
        tbl_data.getTableHeader().setFont(new Font("Yu Gothic UI Semilight", Font.BOLD, 12));
        tbl_data.getTableHeader().setOpaque(false);
        tbl_data.getTableHeader().setBackground(new Color(205, 220, 234));
    }
    
    private void tampilkanData(){
        try {
            ResultSet rs = db.ambilData("select * from transaksi");
            SimpleDateFormat formatTampil = new SimpleDateFormat("dd MMMM yyyy", new Locale("id", "ID"));
            while (rs.next()) { 
                NumberFormat kursIndo = NumberFormat.getIntegerInstance(new Locale("id", "ID"));
                int total = rs.getInt("total");
                int bayar = rs.getInt("bayar");
                int kembali = rs.getInt("kembali");
                
                model.addRow(new Object[]{
                    rs.getString("id"),
                    formatTampil.format(rs.getDate("tanggal")),
                    kursIndo.format(total),
                    kursIndo.format(bayar),
                    kursIndo.format(kembali)
                });
                tbl_data.setModel(model);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtgl1 = new javax.swing.JTextField();
        jtgl2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        btn_kembali = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("data");

        jLabel4.setFont(new java.awt.Font("Goudy Stout", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("penjualan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(643, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(637, 637, 637))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jtgl1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        jtgl2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("s.d");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanggal:");

        tbl_data.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.setRowHeight(30);
        jScrollPane2.setViewportView(tbl_data);

        btn_kembali.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        btn_kembali.setText("Kembali (alt F3)");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        btn_cari.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        btn_cari.setText("Cari (alt F1)");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_refresh.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        btn_refresh.setText("Muat Ulang (alt F2)");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtgl1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtgl2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtgl1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jtgl2)
                    .addComponent(btn_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        FormTrans formKasir = new FormTrans();
        formKasir.setVisible(true);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        try {
            model.setRowCount(0);
            String tgl1Input = jtgl1.getText().trim();
            String tgl2Input = jtgl2.getText().trim();
            
            SimpleDateFormat formatInput = new SimpleDateFormat("dd MMMM yyyy", new Locale("id", "ID"));
            SimpleDateFormat formatDB = new SimpleDateFormat("yyyy-MM-dd");
            
            Date dateAwal = formatInput.parse(tgl1Input);
            Date dateAkhir = formatInput.parse(tgl2Input);
            
            String tglAwalSQL = formatDB.format(dateAwal);
            String tglAkhirSQL = formatDB.format(dateAkhir );
            
            ResultSet rs = db.ambilData("select * from transaksi where tanggal between '"+tglAwalSQL+"' and '"+tglAkhirSQL+"' order by tanggal ASC");
            SimpleDateFormat formatTampil = new SimpleDateFormat("dd MMMM yyyy", new Locale("id", "ID"));
            while (rs.next()) {
                NumberFormat kursIndo = NumberFormat.getIntegerInstance(new Locale("id", "ID"));
                int total = rs.getInt("total");
                int bayar = rs.getInt("bayar");
                int kembali = rs.getInt("kembali");
                
                model.addRow(new Object[]{
                    rs.getString("id"),
                    formatTampil.format(rs.getDate("tanggal")),
                    kursIndo.format(total),
                    kursIndo.format(bayar),
                    kursIndo.format(kembali)
                });
                tbl_data.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        try {
            model.setRowCount(0);
            ResultSet rs = db.ambilData("select * from transaksi");
            SimpleDateFormat formatTampil = new SimpleDateFormat("dd MMMM yyyy", new Locale("id", "ID"));
            while (rs.next()) {                
                NumberFormat kursIndo = NumberFormat.getIntegerInstance(new Locale("id", "ID"));
                int total = rs.getInt("total");
                int bayar = rs.getInt("bayar");
                int kembali = rs.getInt("kembali");
                
                model.addRow(new Object[]{
                    rs.getString("id"),
                    formatTampil.format(rs.getDate("tanggal")),
                    kursIndo.format(total),
                    kursIndo.format(bayar),
                    kursIndo.format(kembali)
                });
                tbl_data.setModel(model);
                jtgl1.setText("");
                jtgl2.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataTrans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtgl1;
    private javax.swing.JTextField jtgl2;
    private javax.swing.JTable tbl_data;
    // End of variables declaration//GEN-END:variables
}
